ALTER TABLE "EmailSignalRule" ALTER COLUMN "query" DROP NOT NULL;

ALTER TABLE "EmailSignalRule"
ADD COLUMN "fetchStrategy" TEXT NOT NULL DEFAULT 'query',
ADD COLUMN "lookbackDays" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN "maxMessagesPerSync" INTEGER NOT NULL DEFAULT 25,
ADD COLUMN "maxEventsPerSync" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN "classifierMode" TEXT NOT NULL DEFAULT 'rules',
ADD COLUMN "minAutoLogConfidence" DOUBLE PRECISION NOT NULL DEFAULT 0.9,
ADD COLUMN "minReviewConfidence" DOUBLE PRECISION NOT NULL DEFAULT 0.65;
