ALTER TABLE "NotificationSettings"
ADD COLUMN "defaultActionTimeMinutes" INTEGER NOT NULL DEFAULT 540,
ADD COLUMN "morningTimeMinutes" INTEGER NOT NULL DEFAULT 540,
ADD COLUMN "afternoonTimeMinutes" INTEGER NOT NULL DEFAULT 900,
ADD COLUMN "eveningTimeMinutes" INTEGER NOT NULL DEFAULT 1140,
ADD COLUMN "tonightTimeMinutes" INTEGER NOT NULL DEFAULT 1200;
